@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImEyYWU0OWExLWE4MTktNDZiNy05NTY5LTlkOTU4NGFmYWI1MCIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjUwODI2Njk4LCJleHAiOjE2NTA4MjY5OTh9.nnjNwOgMflpl4A9aK7ZIxqHSJEHwm2Upt2WvWpeU3Ik
@host = localhost:4005

// Submit a user review
POST http://{{host}}/api/v1/review HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "review": "First review",
  "star": "1",
  "recommendation": false
}

###

// Edit a user review
PUT http://{{host}}/api/v1/review HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "review": "Second Review",
  "star": "5",
  "recommendation": true
}

###

// Delete a user review
DELETE http://{{host}}/api/v1/review HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

###

// Get all user reviews
GET http://{{host}}/api/v1/review HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

