@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM1Y2RmY2Y5LWM3YWQtNDJlMi1iNDAyLTM4NmVmNzk2MzFlOSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjUwNTc0MzI0LCJleHAiOjE2NTA1NzQ2MjR9.EfWSoHtfHnzEd_rfmXcXmCihtGSEifaITXsFNZsfw50
@host = localhost:4005

// Submit a user review
POST http://{{host}}/api/v1/review HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "review": "First review",
  "star": "1",
  "recommendation": false
}

###

// Edit a user review
PUT http://{{host}}/api/v1/review HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "review": "Second Review",
  "star": "5",
  "recommendation": true
}

###

// Delete a user review
DELETE http://{{host}}/api/v1/review HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

###


