@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNmZjkxNmRlLWY1ODAtNDY1YS1iMzFiLTQyMjU1YzVkOWY0YyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY1MDgyNjUxOCwiZXhwIjoxNjUwODI2ODE4fQ.gX6d8LeYsiIGdnZaV90pnFbh8a5geS3QTFve8tj7UAM
@refresh_token = rtoken
@email_token = etoken
@host = localhost:4005

// Register new user
POST http://{{host}}/api/v1/user/register HTTP/1.1
content-type: application/json

{
  "name": "Sagar Padiya",
  "username": "sagarpadiya1",
  "email": "vignesh6993@live.in",
  "password": "Dragon555",
  "repeatPassword": "Dragon555"
}

###

// Resend confirmation email when user remembers email
POST http://{{host}}/api/v1/user/resend-email HTTP/1.1
content-type: application/json

{
  "emailOrUsername": "vignesh6993@live.in"
}
###

// Resend confirmation email when user remembers username
POST http://{{host}}/api/v1/user/resend-email HTTP/1.1
content-type: application/json

{
  "emailOrUsername": "sagarpadiya"
}


###

// Login using username and password
POST http://{{host}}/api/v1/user/login HTTP/1.1
content-type: application/json

{
  "emailOrUsername": "sagarpadiya",
  "password": "Sagar#123"
}

###

// Login using email and password
POST http://{{host}}/api/v1/user/login HTTP/1.1
content-type: application/json

{
  "emailOrUsername": "vignesh6993@live.in",
  "password": "Dragon555"
}
###

// Logout user
GET http://{{host}}/api/v1/user/logout HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

###

GET http://{{host}}/api/v1/user/confirmation/{{email_token}} HTTP/1.1
content-type: application/json

###

DELETE http://{{host}}/api/v1/user/b24376e4-6b8c-41f7-a61c-55a76ff0730b HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "password": "Sagar#123"
}

###

GET http://{{host}}/api/v1/user/refresh HTTP/1.1
content-type: application/json

###
